apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdb-persistent-volume-claim
spec:
  accessModes: 
    - ReadWriteOnce
      #ReadOnlyMany
      #ReadWriteMany
  resources:
    requests:
      storage: 2Gi